### ISSUE TITLE
How to run this with rubenv/pgtest?

### ISSUE THREAD

**Issue by karelbilek** [peterldowns/pgtestdb#1]
Hello,

I am using `rubenv/pgtest` which does the legwork of creating RAM-only DB for me. How to use it together with this package?

You have it in the doc, but I cannot figure it out.

I use pgtest like this

```
	pg, err := pgtest.Start()
	if err != nil {
		t.Error(err)
	}
        db := pg.DB
        // continue with migrations
```

I have no idea what name, password, db is pgtest using.

**Comment by peterldowns** [comment]
Hey Karel, nice to run into you again. Thanks for checking out this project and for asking this question. Details below but short answer is: it's possible but not easy, see the example code. I strongly recommend managing the lifecycle of the postgres server using Docker or some other script rather than `rubenv/pgtest`.

One of the reasons not to try to launch postgres from golang code, but to instead manage it outside of the test suite, is that you probably have multiple different packages you want to test. With `rubenv/pgtest` (and similar methods of starting containers or databases from within golang code), you'll have to copy that `TestMain()` method around, or extract it to a library and call it from a `TestMain` function in every single package you want to test. That's a pain and a waste of resources. `pgtestdb` works best if there is just one server that you use for all your tests, because the template database lives on the server, and you can test as many packages as you want in parallel and they'll all use the same server and template. If you use `rubenv/pgtest` or other similar libraries, you'll end up with multiple different servers, each with their own template database, and you'll have to pay the cost of running migrations multiple times.

---

Working code:

```go
package main

import (
	"database/sql"
	"fmt"
	"os/user"
	"testing"

	"github.com/peterldowns/pgtestdb"
	"github.com/peterldowns/testy/check"
	"github.com/rubenv/pgtest"

	_ "github.com/jackc/pgx/v5/stdlib"
)

var config pgtestdb.Config = pgtestdb.Config{
	DriverName: "pgx",
}

func TestMain(m *testing.M) {
	pg, err := pgtest.Start()
	config.Options = fmt.Sprintf("host=%s", pg.Host)
	config.Database = pg.Name
	config.User = pg.User
	if config.User == "" {
		curUser, err := user.Current()
		if err != nil {
			panic(err)
		}
		config.User = curUser.Username
	}
	if err != nil {
		panic(err)
	}
	defer func() {
		if err := pg.Stop(); err != nil {
			panic(err)
		}
	}()
	m.Run()
}

func NewDB(t *testing.T) *sql.DB {
	t.Helper()
	t.Logf("connecting to %s\n", config.URL())
	migrator := pgtestdb.NoopMigrator{}
	return pgtestdb.New(t, config, migrator)
}

func TestAQuery(t *testing.T) {
	t.Parallel()
	db := NewDB(t)
	var result string
	err := db.QueryRow("SELECT 'hello world'").Scan(&result)
	check.Nil(t, err)
	check.Equal(t, "hello world", result)
}
```

I figured this out by looking at the `pg` variable that `rubenv/pgtest` gives you, and reading the code it uses to create a connection string. If you drop a debugger in the pgtest code, [for instance this line](https://github.com/rubenv/pgtest/blob/f11ffeff9c618877b391a7631e009e16003e2683/pgtest.go#L180), you'll see the DSN it generates looks like this:

```
"host=/var/folders/2d/sv07yzkj71xfjh86ynxr3c180000gn/T/pgtest2326801402/sock dbname=test "
```

In this format, you don't have to specify a user or password because it will implicitly default to the current unix user name, and the `postgres` process it starts will be owned by the current user, so permissions "just work".

In the DSN connection format that `pgtestdb` generates, you must specify a username, so I added some code to figure that out. The rest of the info comes from the `pg` struct per [the source code](https://github.com/rubenv/pgtest/blob/master/pgtest.go#L28).

**Comment by peterldowns** [comment]
Another major issue with `rubenv/pgtest` is that it can leak `postgres` processes if a test crashes or is killed, for instance when you're debugging and abort the test run. `pgtestdb` will work with any running postgres server but for all of the reasons I've written here I recommend using something other than `rubenv/pgtest`, which is not a good library.

Thanks again for reminding me to remove it from the README here.
